#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by Grako.
#
#    https://pypi.python.org/pypi/grako/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.


from __future__ import print_function, division, absolute_import, unicode_literals

from grako.buffering import Buffer
from grako.parsing import graken, Parser
from grako.util import re, RE_FLAGS, generic_main  # noqa


__all__ = [
    'jasParser',
    'jasSemantics',
    'main'
]

KEYWORDS = {}


class jasBuffer(Buffer):
    def __init__(
        self,
        text,
        whitespace=None,
        nameguard=None,
        comments_re=None,
        eol_comments_re=None,
        ignorecase=None,
        namechars='',
        **kwargs
    ):
        super(jasBuffer, self).__init__(
            text,
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            namechars=namechars,
            **kwargs
        )


class jasParser(Parser):
    def __init__(
        self,
        whitespace=None,
        nameguard=None,
        comments_re=None,
        eol_comments_re=None,
        ignorecase=None,
        left_recursion=False,
        parseinfo=True,
        keywords=None,
        namechars='',
        buffer_class=jasBuffer,
        **kwargs
    ):
        if keywords is None:
            keywords = KEYWORDS
        super(jasParser, self).__init__(
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            left_recursion=left_recursion,
            parseinfo=parseinfo,
            keywords=keywords,
            namechars=namechars,
            buffer_class=buffer_class,
            **kwargs
        )

    @graken()
    def _jas_(self):

        def block1():
            with self._ifnot():
                with self._group():
                    self._name_()
                    self._define_()
            with self._ifnot():
                self._begin_()
            self._any_()
        self._closure(block1)
        self.name_last_node('head')
        with self._optional():
            self._meta_()
        self.name_last_node('metas')

        def block4():
            self._type_()
        self._positive_closure(block4)
        self.name_last_node('types')
        self._check_eof()
        self.ast._define(
            ['head', 'metas', 'types'],
            []
        )

    @graken()
    def _meta_(self):
        self._begin_()

        def block0():
            with self._ifnot():
                self._end_()
            with self._optional():
                with self._optional():
                    self._WS_()
                self._NL_()
            self._KVal_()
            self.name_last_node('@')
        self._closure(block0)
        self._end_()

    @graken()
    def _begin_(self):
        self._token('/*')

    @graken()
    def _end_(self):
        self._token('*/')

    @graken()
    def _KVal_(self):
        self._name_()
        self.name_last_node('key')
        self._token(':')

        def block2():
            self._Val_()
        self._positive_closure(block2)
        self.name_last_node('val')
        self.ast._define(
            ['key', 'val'],
            []
        )

    @graken()
    def _Val_(self):
        self._WS_()
        self._pattern(r'.*')
        self.name_last_node('@')
        self._NL_()

    @graken()
    def _WS_(self):
        self._pattern(r'\s+')

    @graken()
    def _NL_(self):
        self._pattern(r'(\n|\r)+')

    @graken()
    def _type_(self):
        self._name_()
        self.name_last_node('name')
        self._define_()
        self._name_()
        self.name_last_node('type')
        with self._optional():
            self._topts_()
            self.name_last_node('topts')
        with self._optional():
            self._cmt_()
            self.name_last_node('td1')
        with self._optional():
            self._fields_()
            self.name_last_node('f')
        self.ast._define(
            ['f', 'name', 'td1', 'topts', 'type'],
            []
        )

    @graken()
    def _any_(self):
        self._pattern(r'(\w|_|-)+|\s+|.')

    @graken()
    def _name_(self):
        self._pattern(r'(\w|_|-)+')

    @graken()
    def _qname_(self):
        self._pattern(r'(\w+:)?(\w|_|-)+')

    @graken()
    def _int_(self):
        self._pattern(r'\d+')

    @graken()
    def _define_(self):
        self._token('::=')

    @graken()
    def _cmt_(self):
        self._token('--')
        self._pattern(r'\s*')
        self._pattern(r'.*')
        self.name_last_node('@')

    @graken()
    def _str_(self):
        self._token('"')

        def block1():
            with self._ifnot():
                self._token('"')
            self._pattern(r'.')
        self._closure(block1)
        self.name_last_node('@')
        self._token('"')

    @graken()
    def _fields_(self):
        self._token('{')
        with self._optional():
            self._cmt_()
            self.name_last_node('td2')

        def sep2():
            self._token(',')

        def block2():
            self._field_()
        self._closure(block2, sep=sep2)
        self.name_last_node('fields')
        self._token('}')
        self.ast._define(
            ['fields', 'td2'],
            []
        )

    @graken()
    def _field_(self):
        with self._choice():
            with self._option():
                with self._group():
                    with self._optional():
                        self._cmt_()
                        self.name_last_node('fd1')
                    self._qname_()
                    self.name_last_node('name')
                    self._etag_()
                    self.name_last_node('tag')
                    with self._optional():
                        self._cmt_()
                        self.name_last_node('fd2')
            with self._option():
                with self._group():
                    with self._optional():
                        self._cmt_()
                        self.name_last_node('fd1')
                    with self._group():
                        with self._choice():
                            with self._option():
                                self._qname_()
                            with self._option():
                                self._token('*')
                            self._error('expecting one of: *')
                    self.name_last_node('name')
                    with self._optional():
                        self._ftag_()
                        self.name_last_node('tag')
                    self._qname_()
                    self.name_last_node('type')
                    with self._optional():
                        self._fopts_()
                        self.name_last_node('fopts')
                    with self._optional():
                        self._cmt_()
                        self.name_last_node('fd2')
            self._error('no available options')
        self.ast._define(
            ['fd1', 'fd2', 'fopts', 'name', 'tag', 'type'],
            []
        )

    @graken()
    def _etag_(self):
        self._token('(')
        self._int_()
        self.name_last_node('@')
        self._token(')')

    @graken()
    def _ftag_(self):
        self._token('[')
        self._int_()
        self.name_last_node('@')
        self._token(']')

    @graken()
    def _pattern_(self):
        self._token('(')
        with self._group():
            self._token('PATTERN')
            self._str_()
        self.name_last_node('@')
        self._token(')')

    @graken()
    def _topts_(self):

        def block0():
            self._pattern_()
        self._positive_closure(block0)

    @graken()
    def _fopts_(self):

        def block0():
            with self._choice():
                with self._option():
                    self._token('OPTIONAL')
                with self._option():
                    self._token('MIN')
                    self._int_()
                with self._option():
                    self._token('MAX')
                    self._int_()
                with self._option():
                    self._token('.&')
                    self._name_()
                self._error('expecting one of: OPTIONAL')
        self._positive_closure(block0)


class jasSemantics(object):
    def jas(self, ast):
        return ast

    def meta(self, ast):
        return ast

    def begin(self, ast):
        return ast

    def end(self, ast):
        return ast

    def KVal(self, ast):
        return ast

    def Val(self, ast):
        return ast

    def WS(self, ast):
        return ast

    def NL(self, ast):
        return ast

    def type(self, ast):
        return ast

    def any(self, ast):
        return ast

    def name(self, ast):
        return ast

    def qname(self, ast):
        return ast

    def int(self, ast):
        return ast

    def define(self, ast):
        return ast

    def cmt(self, ast):
        return ast

    def str(self, ast):
        return ast

    def fields(self, ast):
        return ast

    def field(self, ast):
        return ast

    def etag(self, ast):
        return ast

    def ftag(self, ast):
        return ast

    def pattern(self, ast):
        return ast

    def topts(self, ast):
        return ast

    def fopts(self, ast):
        return ast


def main(filename, startrule, **kwargs):
    with open(filename) as f:
        text = f.read()
    parser = jasParser(parseinfo=False)
    return parser.parse(text, startrule, filename=filename, **kwargs)

if __name__ == '__main__':
    import json
    ast = generic_main(main, jasParser, name='jas')
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(ast, indent=2))
    print()
